### ISSUE TITLE
Brew not installing 6.8

### ISSUE THREAD

**Issue by parljohn** [phpv8/homebrew-tap#3]
Getting the following error when installing 6.8:

gclient sync -vvv --reset -j 8 -r 6.8.275.13
==> gn gen out.gn/x64.release --args="is_debug=false is_official_build=true is_component_build=true use_allocator_shim=false v8_use_external
Last 15 lines from /Users/pjohnson/Library/Logs/Homebrew/v8@6.8/04.x64.release:
          10.12 SDK. For more information, see https://crbug.com/620127.

 Current SDK Version:   10.14
 Current Xcode Version: 0101 (10B61)
********************************************************************************
ERROR at //build/config/mac/mac_sdk.gni:98:3: Assertion failed.
  assert(false, "SDK is incompatible with Xcode")
  ^-----
SDK is incompatible with Xcode

**Comment by pinepain** [comment]
Hi, sorry for late reply. Yeah, apparently sth is broken with v8 and xcode and brief googling shows that it's the case - https://github.com/Homebrew/homebrew-core/issues/31616. In this referenced issue it's been told that the fix didn't make it to v8 6.8, so unfortunately there is no fix for this, sorry.

Closing as unable to fix due to the issue in the upstream. I'll try to come up with fresh v8 version here.
