### ISSUE TITLE
Error: Calling needs :cxx14 is disabled! There is no replacement.

### ISSUE THREAD

**Issue by andyvanee** [phpv8/homebrew-tap#4]
A recent change in Homebrew causes this tap to throw an error.

In the following commit, `cxx14` is removed (among other things) which is referenced in this tap.

<https://github.com/Homebrew/brew/commit/1aa8ad09e212cd9cd2f3ae55f899ed4ef03ae4d0#diff-170833a90b8b2d765544fc2166af6bf5>

<https://github.com/phpv8/homebrew-tap/blob/master/Formula/v8%406.8.rb#L18>

I don't currently have phpv8 installed, and I wasn't trying to install it but simply running `brew cleanup`. I did have it tapped, though, which is why the issue appeared. I'm currently using docker to run it as I had issues installing with Homebrew.

Thanks!

**Comment by pinepain** [comment]
@andyvanee Hi Andy! Thank you for reporting this. I currently do not use this tap anymore (as well as any of it dependencies), though I'll try to look into. 

So far basic patching fixed the tap, however as it came up in #3, none of v8 formulae are buildable anymore, I'll try to come up with fresh v8 version. 

Could you please specify what do you use v8 (is it php-v8 or v8js or sth else?) and are you tied to specific v8 version only or bumping to some recent version would work for you ok?

**Comment by andyvanee** [comment]
No problem!

I am currently prototyping a system that's using v8js, but I am curious about php-v8 as well.

This is my current Dockerfile for building v8js with reasonably up-to-date PHP and V8 versions. <https://gist.github.com/andyvanee/d0abd09f681b18b2eeae749b6885a04d>

The main thing I was looking for was a reasonably recent V8 version with ES6 support, and this combination of versions seems to be working fine.

**Comment by pinepain** [comment]
From what i read the macos issue is fixed in 6.9.sth, though, you know, v8 moving forward is very fast and from my experience mainlining sth that relies on it is a bit pita. I'm not 100% sure that php-v8 would work out of the box with latest v8 version, haven't run it for a long time already, but if you'll be there to give it a try, pls let me know how it works. Also, for macos, you can just copy one of formulae here and just bump it version (rename file name, ruby classname, git version and sha and probably bump `depot_tools` commit hash to sth more recent). If it would work, then you may even PR it if you have time for this, I would really appreciate it as i'm not sure when I will have time to get to this and test that new v8 builds myself.

**Comment by andyvanee** [comment]
Yes, it seems like finding versions of PHP/V8 and V8Js that all work together is a moving target. I assume that the same compatibility issues affect anything that depends on V8. If I have time, I will do some more testing and let you know what I find. For now, I can confirm that the reported error is gone. Thanks!
